# Generated by Django 3.1.5 on 2021-01-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210120_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question',
        ),
    ]
