# Generated by Django 3.1.5 on 2021-01-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210122_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='divisions',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='divisions',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='division',
            new_name='section',
        ),
    ]
